### ISSUE TITLE
Error loading 'rj' package on start

### ISSUE THREAD

**Issue by Rickasaurus** [openanalytics/architect#2]
With a fresh R 3.2.1 install on Windows 8.1 x64 Architect fails on startup with:

Launching the R Console was cancelled, because it seems starting the R engine failed. 
Please make sure that R package 'rj' (2.0 or compatible) is installed and that the R library paths are set correctly for the R environment configuration 'Embedded R Server'.
Process Error Log:
Jun 30, 2015 8:18:51 PM de.walware.rj.server.RMIServerControl start
INFO: [Control:rjs-local-1435709931201] initialize server...
Jun 30, 2015 8:18:51 PM de.walware.rj.server.jri.loader.JRIClassLoader <init>
SEVERE: Path to rj package not found. Use R_LIBS or java property 'de.walware.rj.rpkg.path' to specify the location.
Jun 30, 2015 8:18:51 PM de.walware.rj.server.srvImpl.AbstractServerControl initREngine
SEVERE: [Control:rjs-local-1435709931201] init JRI/Rengine failed.
java.lang.RuntimeException: Path to rj package not found. Use R_LIBS or java property 'de.walware.rj.rpkg.path' to specify the location.
    at de.walware.rj.server.jri.loader.JRIClassLoader.<init>(JRIClassLoader.java:278)
    at RJavaClassLoader.<init>(RJavaClassLoader.java:47)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at de.walware.rj.server.jri.loader.JRIClassLoader.getRJavaClassLoader(JRIClassLoader.java:46)
    at de.walware.rj.server.jri.loader.JRIServerLoader.loadServer(JRIServerLoader.java:48)
    at de.walware.rj.server.srvImpl.AbstractServerControl.initREngine(AbstractServerControl.java:216)
    at de.walware.rj.server.RMIServerControl.start(RMIServerControl.java:103)
    at de.walware.rj.server.RMIServerControl.main(RMIServerControl.java:40)

Jun 30, 2015 8:18:51 PM de.walware.rj.server.srvImpl.AbstractServerControl initVerbose
CONFIG: verbose mode enabled.
Jun 30, 2015 8:18:51 PM de.walware.rj.server.srvImpl.AbstractServerControl initVerbose
CONFIG: java properties:
    java.runtime.name=Java(TM) SE Runtime Environment
    sun.boot.library.path=C:\Program Files\Java\jre1.8.0_45\bin
    java.vm.version=25.45-b02
    java.vm.vendor=Oracle Corporation
    java.vendor.url=http://java.oracle.com/
    path.separator=;
    java.vm.name=Java HotSpot(TM) 64-Bit Server VM
    file.encoding.pkg=sun.io
    user.country=US
    user.script=
    sun.java.launcher=SUN_STANDARD
    sun.os.patch.level=
    java.vm.specification.name=Java Virtual Machine Specification
    user.dir=C:\Program Files\Architect
    java.runtime.version=1.8.0_45-b15
    java.awt.graphicsenv=sun.awt.Win32GraphicsEnvironment
    java.endorsed.dirs=C:\Program Files\Java\jre1.8.0_45\lib\endorsed
    os.arch=amd64
    java.io.tmpdir=C:\Windows\
    line.separator=

```
java.vm.specification.vendor=Oracle Corporation
user.variant=
os.name=Windows 8.1
sun.jnu.encoding=Cp1252
java.library.path=C:\Program Files\Java\jre1.8.0_45\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;.
java.specification.name=Java Platform API Specification
java.class.version=52.0
sun.management.compiler=HotSpot 64-Bit Tiered Compilers
os.version=6.3
user.home=C:\Users\rminerich
java.security.policy=jar:file:/C:/Program Files/Architect/plugins/de.walware.rj.server_2.0.2.b201506211449E44sw.jar!/localhost.policy
user.timezone=America/New_York
java.awt.printerjob=sun.awt.windows.WPrinterJob
file.encoding=Cp1252
java.specification.version=1.8
de.walware.rj.rmi.disableSocketFactory=true
java.class.path=/C:/Program Files/Architect/plugins/de.walware.rj.server_2.0.2.b201506211449E44sw.jar;/C:/Program Files/Architect/plugins/de.walware.rj.data_2.0.0.b201506211449E44sw.jar;/C:/Program Files/Architect/plugins/org.eclipse.swt_3.103.2.v20150203-1313.jar;/C:/Program Files/Architect/plugins/org.eclipse.swt.win32.win32.x86_64_3.103.2.v20150203-1351.jar
user.name=rminerich
java.vm.specification.version=1.8
sun.java.command=de.walware.rj.server.RMIServerControl start rmi://127.0.0.1:51234/rjs-local-1435709931201 -auth=none -embedded -plugins=awt,swt,
java.home=C:\Program Files\Java\jre1.8.0_45
sun.arch.data.model=64
user.language=en
java.specification.vendor=Oracle Corporation
awt.toolkit=sun.awt.windows.WToolkit
java.vm.info=mixed mode
java.version=1.8.0_45
java.ext.dirs=C:\Program Files\Java\jre1.8.0_45\lib\ext;C:\Windows\Sun\Java\lib\ext
sun.boot.class.path=C:\Program Files\Java\jre1.8.0_45\lib\resources.jar;C:\Program Files\Java\jre1.8.0_45\lib\rt.jar;C:\Program Files\Java\jre1.8.0_45\lib\sunrsasign.jar;C:\Program Files\Java\jre1.8.0_45\lib\jsse.jar;C:\Program Files\Java\jre1.8.0_45\lib\jce.jar;C:\Program Files\Java\jre1.8.0_45\lib\charsets.jar;C:\Program Files\Java\jre1.8.0_45\lib\jfr.jar;C:\Program Files\Java\jre1.8.0_45\classes
java.vendor=Oracle Corporation
file.separator=\
java.vendor.url.bug=http://bugreport.sun.com/bugreport/
sun.io.unicode.encoding=UnicodeLittle
sun.cpu.endian=little
java.rmi.server.hostname=127.0.0.1
sun.desktop=windows
sun.cpu.isalist=amd64
```

Jun 30, 2015 8:18:51 PM de.walware.rj.server.srvImpl.AbstractServerControl initVerbose
CONFIG: env variables:
    SystemRoot=C:\Windows

**Comment by Rickasaurus** [comment]
I attempted to install the "rj" package as requested but it doesn't seem to exist. 

> install.packages('rj')
> Warning message:
> package ‘rj’ is not available (for R version 3.2.1)

**Comment by linhnd1303** [comment]
here is the solution. please read carefully this page and choose right version: http://www.walware.de/goto/statet

**Comment by nlbjan1** [comment]
The resource mentioned above seems to have moved. I'm not having any luck at the moment with installation with the instructions I could find. For new users it would be nice if the existing R installation is picked up from the registery.
